"""Initial schema

Revision ID: 972b44909d71
Revises: 
Create Date: 2025-11-27 07:37:15.943734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972b44909d71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('ssn_last_four', sa.String(length=4), nullable=True),
    sa.Column('is_minor', sa.String(length=1), nullable=True),
    sa.Column('guardian_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estate_documents',
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('attorney_name', sa.String(length=200), nullable=True),
    sa.Column('attorney_firm', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.String(length=1), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('important_contacts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('firm', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('income_type', sa.String(length=50), nullable=False),
    sa.Column('employer', sa.String(length=200), nullable=True),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_log',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_in_file', sa.Integer(), nullable=True),
    sa.Column('records_created', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_accounts',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'account_id', name='uq_investment_account')
    )
    op.create_table('investment_holdings',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('ingestion_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'account_id', 'symbol', name='uq_holding')
    )
    op.create_table('investment_holdings_history',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'account_id', 'symbol', 'snapshot_date', name='uq_holding_history')
    )
    op.create_table('investment_transactions',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('ingestion_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'account_id', 'transaction_date', 'transaction_type', 'symbol', 'quantity', 'amount', name='uq_investment_transaction')
    )
    op.create_index('idx_transaction_date', 'investment_transactions', ['transaction_date'], unique=False)
    op.create_index('idx_transaction_symbol', 'investment_transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_investment_transactions_record_hash'), 'investment_transactions', ['record_hash'], unique=False)
    op.create_table('properties',
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_value_date', sa.Date(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_properties',
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('parcel_number', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('disposed_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_allocations',
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_description', sa.String(length=500), nullable=True),
    sa.Column('allocation_type', sa.String(length=20), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('allocation_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_contingent', sa.String(length=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income_entries',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('income_type', sa.String(length=50), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pay_period_start', sa.Date(), nullable=True),
    sa.Column('pay_period_end', sa.Date(), nullable=True),
    sa.Column('federal_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('state_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('social_security', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('medicare', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_deductions', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingestion_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['income_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'income_date', 'gross_amount', name='uq_income_entry')
    )
    op.create_index('idx_income_date', 'income_entries', ['income_date'], unique=False)
    op.create_index('idx_income_tax_year', 'income_entries', ['tax_year'], unique=False)
    op.create_table('mortgages',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('lender', sa.String(length=200), nullable=False),
    sa.Column('loan_number', sa.String(length=100), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_as_of_date', sa.Date(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('is_fixed_rate', sa.String(length=1), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('escrow_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=True),
    sa.Column('paid_off_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_tax_records',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('installment', sa.Integer(), nullable=True),
    sa.Column('assessed_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('land_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('improvement_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.String(length=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ingestion_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['tax_properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'tax_year', 'installment', name='uq_property_tax_record')
    )
    op.create_index('idx_tax_year', 'property_tax_records', ['tax_year'], unique=False)
    op.create_table('property_valuations',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valuation_source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_valuation_date', 'property_valuations', ['valuation_date'], unique=False)
    op.create_table('record_provenance',
    sa.Column('ingestion_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_documents',
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['tax_properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortgage_payments',
    sa.Column('mortgage_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('total_payment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('escrow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extra_principal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remaining_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ingestion_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mortgage_id'], ['mortgages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_date', 'mortgage_payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_date', table_name='mortgage_payments')
    op.drop_table('mortgage_payments')
    op.drop_table('tax_documents')
    op.drop_table('record_provenance')
    op.drop_index('idx_valuation_date', table_name='property_valuations')
    op.drop_table('property_valuations')
    op.drop_index('idx_tax_year', table_name='property_tax_records')
    op.drop_table('property_tax_records')
    op.drop_table('mortgages')
    op.drop_index('idx_income_tax_year', table_name='income_entries')
    op.drop_index('idx_income_date', table_name='income_entries')
    op.drop_table('income_entries')
    op.drop_table('asset_allocations')
    op.drop_table('tax_properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_investment_transactions_record_hash'), table_name='investment_transactions')
    op.drop_index('idx_transaction_symbol', table_name='investment_transactions')
    op.drop_index('idx_transaction_date', table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_table('investment_holdings_history')
    op.drop_table('investment_holdings')
    op.drop_table('investment_accounts')
    op.drop_table('ingestion_log')
    op.drop_table('income_sources')
    op.drop_table('important_contacts')
    op.drop_table('estate_documents')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###

