"""add_portfolio_snapshots

Revision ID: 7c06dfb788ae
Revises: 972b44909d71
Create Date: 2025-11-27 10:27:12.911378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c06dfb788ae'
down_revision: Union[str, None] = '972b44909d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('securities_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ingestion_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'account_id', 'statement_date', name='uq_portfolio_snapshot')
    )
    op.create_index('idx_snapshot_date', 'portfolio_snapshots', ['statement_date'], unique=False)
    op.create_index('idx_snapshot_owner', 'portfolio_snapshots', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshot_owner', table_name='portfolio_snapshots')
    op.drop_index('idx_snapshot_date', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###

